targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/features/**/data/models/**.dart
            - lib/shared/models/**.dart
        options:
          explicit_to_json: true
